// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutorial8.Data;

#nullable disable

namespace Tutorial8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516210447_SeedPCComponent")]
    partial class SeedPCComponent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tutorial8.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "INTEL00001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "16-core gaming processor",
                            Name = "Intel Core Ultra 99"
                        },
                        new
                        {
                            Code = "NVIDIA0001",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "Bleeding-edge gaming graphics card",
                            Name = "GeForce RTX 5070"
                        },
                        new
                        {
                            Code = "VIPER00001",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "DDR5 RAM module 64GB",
                            Name = "Viper Venom DDR5 64GB"
                        },
                        new
                        {
                            Code = "AMD0000001",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 1,
                            Description = "mini-core pocket processor",
                            Name = "AMD Ryzen 9 9999X"
                        },
                        new
                        {
                            Code = "VIPER00002",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "DDR5 RAM module 16GB",
                            Name = "Viper Venom DDR5 16GB"
                        },
                        new
                        {
                            Code = "VIPER00003",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "DDR4 RAM module 8GB",
                            Name = "Viper Steel DDR4 8GB"
                        });
                });

            modelBuilder.Entity("Tutorial8.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateOnly(1968, 1, 1),
                            FullName = "Integrated Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NV",
                            FoundationDate = new DateOnly(1993, 1, 1),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PM",
                            FoundationDate = new DateOnly(1985, 1, 1),
                            FullName = "Patriot Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        });
                });

            modelBuilder.Entity("Tutorial8.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("Tutorial8.Entities.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Monster x99",
                            Stock = 69,
                            Warranty = 36,
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pro Office Mini",
                            Stock = 666,
                            Warranty = 24,
                            Weight = 3.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Bargain 13",
                            Stock = 1,
                            Warranty = 12,
                            Weight = 9.0
                        });
                });

            modelBuilder.Entity("Tutorial8.Entities.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "INTEL00001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "NVIDIA0001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "VIPER00001",
                            Amount = 6
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "AMD0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "VIPER00002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "VIPER00003",
                            Amount = 3
                        });
                });

            modelBuilder.Entity("Tutorial8.Entities.Component", b =>
                {
                    b.HasOne("Tutorial8.Entities.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tutorial8.Entities.ComponentType", "Type")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Tutorial8.Entities.PCComponent", b =>
                {
                    b.HasOne("Tutorial8.Entities.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutorial8.Entities.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("Tutorial8.Entities.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("Tutorial8.Entities.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tutorial8.Entities.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tutorial8.Entities.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
